# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: ci
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches:
      - 'main'       # Run the workflow when pushing to the main branch
  pull_request:
    branches:
      - '*'          # Run the workflow for all pull requests
  release:
    types:
      - published    # Run the workflow when a new GitHub release is published

env:
  # Source: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_skip_first_time_experience
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  # Source: https://learn.microsoft.com/en-us/dotnet/core/tools/telemetry#disclosure
  DOTNET_NOLOGO: true
  NUGET_DIR: ${{ github.workspace }}/nuget

defaults:
  run:
    shell: pwsh

jobs:

  # Can't pass env variables to reusable workflow, so we use this hack
  workflow_environment_vars:
    runs-on: ubuntu-latest
    outputs:
      nuget_dir: ${{ env.NUGET_DIR }}
    steps:
      - run: |
          echo "nuget_dir: ${{ env.NUGET_DIR }}"

  create_and_validate_nuget:
    needs: [ workflow_environment_vars ]
    uses: ./.github/workflows/package.yml
    with:
      nuget-dir: ${{ needs.workflow_environment_vars.outputs.nuget_dir }}

  test:
    uses: ./.github/workflows/test.yml
